# -*- coding: utf-8 -*-
"""PythonDeep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LKdByxU161j2aQzbq1503dZ3jM_6zjR2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import os
import cv2
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras import *
from tensorflow import *

path="/content/drive/MyDrive/davidtuto1"
os.listdir(path)

classes= ["Carapuce","Salameche","pikachu","rondoudou"]

data= []
labels=[]
i=0
for j in classes:
  data_dir=path+str("/")+str(j)
  for img in os.listdir(data_dir):
    pic = cv2.imread(os.path.join(data_dir,img))
    pic = cv2.cvtColor(pic,cv2.COLOR_BGR2RGB)
    pic = cv2.resize(pic,(28,28))
    image=np.array(pic).flatten()
    data.append([image,j])
    labels.append(j)
    i+=1

feat=[]
lab=[]
for f, l in data:
  feat.append(f)
  lab.append(l)

feature = np.matrix(feat)

encoder_ = LabelEncoder()
y = encoder_.fit_transform(lab)

x_train,x_test,y_train,y_test= train_test_split(feat,y,test_size=0.2)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(input_shape=(None,3,2352),units=128,activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(4,activation="relu")
])

model.summary()

model.compile(
    optimizer='adam',
    loss= tf.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy'])

x_train = np.matrix(x_train)/255

x_test = np.matrix(x_test)/255

model.fit(x_train,y_train,epochs=20,batch_size=3,validation_split=0.2)

